var comp = [
  {
    measurements: [
      {
        unit: {
          system: "imperial",
          name: "tablespoon",
          display_plural: "tablespoons",
          display_singular: "tablespoon",
          abbreviation: "tbsp",
        },
        quantity: "14",
        id: 730978,
      },
      {
        unit: {
          abbreviation: "stick",
          system: "none",
          name: "stick",
          display_plural: "sticks",
          display_singular: "stick",
        },
        quantity: "1 ¾",
        id: 730977,
      },
    ],
    raw_text:
      "14 tablespoons (1¾ sticks) Kerrygold™ Pure Irish Unsalted Butter, softened",
    extra_comment: "softened",
    ingredient: {
      updated_at: 1681833888,
      name: "Kerrygold™ Pure Irish Unsalted Butter",
      created_at: 1681833888,
      display_plural: "Kerrygold™ Pure Irish Unsalted Butters",
      id: 11139,
      display_singular: "Kerrygold™ Pure Irish Unsalted Butter",
    },
    id: 99331,
    position: 1,
  },
  {
    ingredient: {
      id: 419,
      display_singular: "granulated sugar",
      updated_at: 1509035262,
      name: "granulated sugar",
      created_at: 1494989637,
      display_plural: "granulated sugars",
    },
    id: 99332,
    position: 2,
    measurements: [
      {
        unit: {
          name: "cup",
          display_plural: "cups",
          display_singular: "cup",
          abbreviation: "c",
          system: "imperial",
        },
        quantity: "¾",
        id: 730982,
      },
      {
        unit: {
          display_plural: "g",
          display_singular: "g",
          abbreviation: "g",
          system: "metric",
          name: "gram",
        },
        quantity: "150",
        id: 730979,
      },
    ],
    raw_text: "¾ cup granulated sugar",
    extra_comment: "",
  },
  {
    raw_text: "3 tablespoons lemon juice",
    extra_comment: "",
    ingredient: {
      display_plural: "lemon juices",
      id: 271,
      display_singular: "lemon juice",
      updated_at: 1509035274,
      name: "lemon juice",
      created_at: 1494624947,
    },
    id: 99335,
    position: 3,
    measurements: [
      {
        unit: {
          abbreviation: "tbsp",
          system: "imperial",
          name: "tablespoon",
          display_plural: "tablespoons",
          display_singular: "tablespoon",
        },
        quantity: "3",
        id: 730981,
      },
    ],
  },
  {
    raw_text: "1 large egg yolk",
    extra_comment: "",
    ingredient: {
      created_at: 1499974363,
      display_plural: "large egg yolks",
      id: 2073,
      display_singular: "large egg yolk",
      updated_at: 1509035146,
      name: "large egg yolk",
    },
    id: 99333,
    position: 4,
    measurements: [
      {
        id: 730980,
        unit: {
          system: "none",
          name: "",
          display_plural: "",
          display_singular: "",
          abbreviation: "",
        },
        quantity: "1",
      },
    ],
  },
  {
    raw_text: "1 tablespoon lemon zest",
    extra_comment: "",
    ingredient: {
      updated_at: 1518723289,
      name: "lemon zest",
      created_at: 1494124243,
      display_plural: "lemon zests",
      id: 194,
      display_singular: "lemon zest",
    },
    id: 99334,
    position: 5,
    measurements: [
      {
        unit: {
          name: "tablespoon",
          display_plural: "tablespoons",
          display_singular: "tablespoon",
          abbreviation: "tbsp",
          system: "imperial",
        },
        quantity: "1",
        id: 730990,
      },
    ],
  },
  {
    measurements: [
      {
        unit: {
          name: "cup",
          display_plural: "cups",
          display_singular: "cup",
          abbreviation: "c",
          system: "imperial",
        },
        quantity: "1 ½",
        id: 730985,
      },
      {
        quantity: "185",
        id: 730984,
        unit: {
          display_singular: "g",
          abbreviation: "g",
          system: "metric",
          name: "gram",
          display_plural: "g",
        },
      },
    ],
    raw_text: "1½ cups plus 2 tablespoons all-purpose flour",
    extra_comment: "plus 2 tablespoons",
    ingredient: {
      id: 185,
      display_singular: "all-purpose flour",
      updated_at: 1509035280,
      name: "all-purpose flour",
      created_at: 1494122348,
      display_plural: "all-purpose flours",
    },
    id: 99336,
    position: 6,
  },
  {
    raw_text: "½ cup cornstarch",
    extra_comment: "",
    ingredient: {
      created_at: 1495141711,
      display_plural: "cornstarches",
      id: 488,
      display_singular: "cornstarch",
      updated_at: 1509035256,
      name: "cornstarch",
    },
    id: 99337,
    position: 7,
    measurements: [
      {
        unit: {
          system: "imperial",
          name: "cup",
          display_plural: "cups",
          display_singular: "cup",
          abbreviation: "c",
        },
        quantity: "½",
        id: 730992,
      },
      {
        unit: {
          system: "metric",
          name: "gram",
          display_plural: "g",
          display_singular: "g",
          abbreviation: "g",
        },
        quantity: "65",
        id: 730991,
      },
    ],
  },
  {
    raw_text: "¼ teaspoon ground cardamom",
    extra_comment: "",
    ingredient: {
      name: "ground cardamom",
      created_at: 1496957501,
      display_plural: "ground cardamoms",
      id: 1679,
      display_singular: "ground cardamom",
      updated_at: 1509035173,
    },
    id: 99340,
    position: 8,
    measurements: [
      {
        unit: {
          system: "imperial",
          name: "teaspoon",
          display_plural: "teaspoons",
          display_singular: "teaspoon",
          abbreviation: "tsp",
        },
        quantity: "¼",
        id: 730987,
      },
    ],
  },
  {
    raw_text: "¾ teaspoon kosher salt",
    extra_comment: "",
    ingredient: {
      id: 11,
      display_singular: "kosher salt",
      updated_at: 1509035289,
      name: "kosher salt",
      created_at: 1493307153,
      display_plural: "kosher salts",
    },
    id: 99339,
    position: 9,
    measurements: [
      {
        unit: {
          system: "imperial",
          name: "teaspoon",
          display_plural: "teaspoons",
          display_singular: "teaspoon",
          abbreviation: "tsp",
        },
        quantity: "¾",
        id: 730986,
      },
    ],
  },
  {
    measurements: [
      {
        unit: {
          system: "imperial",
          name: "tablespoon",
          display_plural: "tablespoons",
          display_singular: "tablespoon",
          abbreviation: "tbsp",
        },
        quantity: "1",
        id: 730983,
      },
    ],
    raw_text: "1 tablespoon chopped fresh thyme leaves",
    extra_comment: "chopped",
    ingredient: {
      display_plural: "fresh thyme leaves",
      id: 4999,
      display_singular: "fresh thyme leaf",
      updated_at: 1545064023,
      name: "fresh thyme leaves",
      created_at: 1545064023,
    },
    id: 99338,
    position: 10,
  },
  {
    id: 99341,
    position: 11,
    measurements: [
      {
        unit: {
          system: "none",
          name: "",
          display_plural: "",
          display_singular: "",
          abbreviation: "",
        },
        quantity: "28",
        id: 730988,
      },
    ],
    raw_text: "Small fresh thyme sprigs, for garnish",
    extra_comment: "for garnish",
    ingredient: {
      display_plural: "small fresh thyme sprigs",
      id: 11148,
      display_singular: "small fresh thyme sprig",
      updated_at: 1681834847,
      name: "small fresh thyme sprigs",
      created_at: 1681834847,
    },
  },
  {
    raw_text: "Coarse sugar, such as turbinado, for sprinkling",
    extra_comment: "such as turbinado, for sprinkling",
    ingredient: {
      updated_at: 1538620661,
      name: "coarse sugar",
      created_at: 1538620661,
      display_plural: "coarse sugars",
      id: 4773,
      display_singular: "coarse sugar",
    },
    id: 99342,
    position: 12,
    measurements: [
      {
        unit: {
          system: "none",
          name: "",
          display_plural: "",
          display_singular: "",
          abbreviation: "",
        },
        quantity: "0",
        id: 730989,
      },
    ],
  },
];
const words = ["salt.png"];

